akun/urls.py
from django.urls import path, include
from akun import views

app_name = 'akun'

comment_url = [
    path('permanent/delete/comment/<pk>/', views.permanent_delete, name='delete_comment'),
    path('un/delete/comment/<pk>/', views.undelete_comment, name='undelete_comment'),
    path('soft/delete/comment/<pk>/', views.trash_comment, name='trash_comment'),
    path('make/comment/', views.PostComment.as_view(), name='comment_make'),
    path('get/comment/<str:hash>/', views.CommentsView.as_view(), name='comment_view'),
    path('my/comment/', views.MyComments.as_view(), name='my_comment'),
    path('is-spam/comment/delete/', views.all_spam_clean, name='all_spam_delete'),
]

i_update = [
    path('profile/', views.UpdateMyGeneralProfile.as_view(), name='update_profile'),
    path('bio/', views.UpdateOrCreateBio.as_view(), name='update_bio'),
]

urlpatterns = [
    path('comments/', include(comment_url)),
    path('signin/comment/', views.login_from_comment, name='comment_login'),
    path('update/', include(i_update)),
    path('', views.MyAkunView.as_view(), name='dashboard'),
]

corecode/urls.py
from django.urls import path, re_path
from corecode import views

app_name = 'core'

urlpatterns = [
    re_path(r'list/(?P<tagmodel>[\._\w]+)/$', views.list_tags, name='tagging_autocomplete_list'),
    path('dashboard/', views.DashboardStaff.as_view(), name='dashboard'),
    path('', views.cek_user, name='cek_user'),
]

posts/urls.py
from django.urls import path
from corecode.views import KontakViews, PortfolioDetailView, PortfolioListView
from posts import views as pv

app_name = 'blog'

urlpatterns = [
    path('kontak/', KontakViews.as_view(), name='kontak'),
    path('portfolio/<slug>/', PortfolioDetailView.as_view(), name='portf_detail'),
    path('portfolio/', PortfolioListView.as_view(), name='portf_list'),
    path('page/<slug>/', pv.PageViewDetail.as_view(), name='page'),
    path('search/<str:q>', pv.SeacrhTerm.as_view(), name='search'),
    path('<slug>/', pv.TermListView.as_view(), name='term'),
    path('<slug:term>/<slug:post>', pv.PostDetail.as_view(), name='detail'),
    path('', pv.Home.as_view(), name='index'),
]

sibmail/urls.py
from django.urls import path, include
from sibmail import views

app_name = 'sibmail'

get_email = [
    path('get-email-campaigns/', views.MySIBGetEmailCampaigns.as_view(), name='get_email_campaigns'),
]

urlpatterns = [
    path('contact/delete/<str:email>/', views.delete_contact, name='contact_delete'),
    path('contact/create/', views.CreateAContact.as_view(), name='create_contact'),
    path('contact/create/success/', views.success_subscribe, name='sub_success'),
    path('contact/details/', views.MySIBContactDetails.as_view(), name='my_contact_details'),
    path('contact/', views.MySIBContact.as_view(), name='my_contact'),
    path('my-account/', views.MySIBAccount.as_view(), name='sib_account'),
    
    path('get-all-folders/', views.GetAllFolders.as_view(), name='get_all_folders'),
    path('get-list-in-folders/<int:fid>/', views.GetListInFolder.as_view(), name='get_linfold'),

    path('get/', include(get_email)),
]

templates/lte/base.html
{% load i18n static jazzmin admin_urls %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% get_jazzmin_settings request as jazzmin_settings %}
{% get_jazzmin_ui_tweaks as jazzmin_ui %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:'en-us' }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{{ title }} | {{ jazzmin_settings.site_title }} {% endblock %} {{ request.intro.name }}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}">
  <!-- Bootstrap and adminLTE -->
  <link rel="stylesheet" href="{% static 'vendor/adminlte/css/adminlte.min.css' %}" id="adminlte-css">
  <!-- Bootswatch theme -->
  {% if jazzmin_ui.theme.name != 'default' %}
  <link rel="stylesheet" href="{{ jazzmin_ui.theme.src }}" id="jazzmin-theme" />
  {% endif %}

  {% if jazzmin_ui.dark_mode_theme %}
  <link rel="stylesheet" href="{{ jazzmin_ui.dark_mode_theme.src }}" id="jazzmin-dark-mode-theme" media="(prefers-color-scheme: dark)"/>
  {% endif %}

  <!-- Custom fixes for django -->
  <link rel="stylesheet" href="{% static 'jazzmin/css/main.css' %}">
  
  {% if jazzmin_settings.custom_css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static jazzmin_settings.custom_css %}">
  {% endif %}
  
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

  <!-- favicons -->
  <link rel="shortcut icon" href="{% static jazzmin_settings.site_icon %}" type="image/png">
  <link rel="icon" href="{% static jazzmin_settings.site_icon %}" sizes="32x32" type="image/png">
  {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
  
  {% block extrastyle %} {% endblock %}
  {% block extrahead %} {% endblock %}
</head>
<body class="hold-transition sidebar-mini{% sidebar_status request %} {% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %} {{ jazzmin_ui.body_classes }}" data-admin-utc-offset="{% now "Z" %}">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="{% static 'img/logo.png' %}" alt="Edi Kartono" height="60" width="60">
  </div>

  {% if not is_popup %}
  {% include 'lte/navbar.html' %}

  {% include 'lte/sidebar.html' %}
  {% endif %}
  {% block sidebar %}{% endblock %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    {% block page_content %}
    {% if not is_popup %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{% block content_title %}{% endblock %}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              {% block breadcrumbs %}
              {% endblock %}
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    {% endif %}

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <section id="content" class="content">
          {% block messages %}
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button>
              <i class="icon fa fa-check"></i>{{ message|capfirst }}
            </div>
            {% endfor %}
          {% endblock messages %}
          <div class="row">
            {% block content %}{% endblock %}
          </div>
        </section>
      </div><!--/. container-fluid -->
    </div>
    <!-- /.content -->
    {% endblock %}
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  {% block footer %}
  {% if not is_popup %}
      <footer class="main-footer {{ jazzmin_ui.footer_classes }}">
          <div class="float-right d-none d-sm-inline">
              {% comment %} <b>{% trans 'Jazzmin version' %}</b> {% get_jazzmin_version %} {% endcomment %}
              <b>{% trans 'Versi' %}</b> 1.1.0
          </div>
          {% autoescape off %}
              <strong>&copy; {% now 'Y' %} {{ jazzmin_settings.copyright }}.</strong> {% trans 'All rights reserved.' %}
          {% endautoescape %}
      </footer>
      {% if jazzmin_settings.show_ui_builder %}
          {% include 'jazzmin/includes/ui_builder_panel.html' %}
      {% endif %}
  {% endif %}
  {% endblock %}
</div>
<!-- ./wrapper -->

<!-- ./wrapper -->
{% if jazzmin_settings.show_ui_builder %}
<div id="codeBox" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{% trans 'UI Configuration' %}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <p>{% trans 'Copy this info your settings file to persist these UI changes' %}</p>
                <pre><code></code></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn {{ jazzmin_ui.button_classes.danger }}" data-dismiss="modal">{% trans 'Close' %}</button>
            </div>
        </div>

    </div>
</div>
{% endif %}
<div id="myModal" class="modal" role="dialog"></div>
<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<!-- <script src="{% static "admin/js/vendor/jquery/jquery.js" %}"></script> -->
<!-- Bootstrap 4 -->
<!-- <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script> -->
<!-- AdminLTE App -->
<!-- <script src="{% static "vendor/adminlte/js/adminlte.min.js" %}"></script> -->
<!-- Django customisations -->
<!-- <script src="{% static "jazzmin/js/main.js" %}"></script> -->

<!-- jQuery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'vendor/adminlte/js/adminlte.min.js' %}"></script>
<!-- Django customisations -->
<script src="{% static 'jazzmin/js/main.js' %}"></script>

<!-- <script>
  $.widget.bridge('uibutton', $.ui.button)
</script> -->
{% if jazzmin_settings.custom_js %}
<script src="{% static jazzmin_settings.custom_js %}"></script>
{% endif %}

<!-- {% if jazzmin_settings.show_ui_builder %}
<script>
    window.ui_changes = {{ jazzmin_ui.raw|as_json|safe }};
</script>
<script src="{% static 'jazzmin/js/ui-builder.js' %}"></script>
{% endif %} -->

{% block extrajs %}{% endblock %}
</body>
</html>

templates/lte/navbar.html
{% load i18n static jazzmin admin_urls %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'blog:index' %}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'blog:kontak' %}" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
        
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
      
        <li class="nav-item dropdown">
            <a class="nav-link btn" data-toggle="dropdown" href="#" title="{{ request.user }}">
                <i class="far fa-user pr-2" aria-hidden="true"></i>
            </a>
        
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-left" id="jazzy-usermenu">
                <span class="dropdown-header">{% trans 'Account' %}</span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'account_change_password' %}" class="dropdown-item">
                    <i class="fas fa-key mr-2"></i> {% trans 'Change password' %}
                </a>

                <div class="dropdown-divider"></div>
                <a href="{% url 'account_logout' %}" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> {% trans 'Log out' %}
                </a>
            
                {% get_user_menu user request.current_app|default:"admin" as user_menu %}
                {% for link in user_menu %}
                <div class="dropdown-divider"></div>
                <a href="{{ link.url }}" class="dropdown-item" {% if link.new_window %}target="_blank"{% endif %}>
                    <i class="{{ link.icon }} mr-2"></i> {% trans link.name %}
                </a>
                {% endfor %}
            
                <div class="dropdown-divider"></div>
                {% if perms|can_view_self %}
                <a href="{% jazzy_admin_url request.user request.current_app|default:'admin' %}" class="dropdown-item dropdown-footer">{% trans 'See Profile' %}</a>
                {% endif %}
            </div>
        </li>
      
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
      
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

templates/lte/sidebar.html
{% load i18n static jazzmin admin_urls %}
{% get_jazzmin_settings request as jazzmin_settings %}
{% get_side_menu as side_menu_list %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar elevation-4 {{ jazzmin_ui.sidebar_classes }}" id="jazzy-sidebar">
  <a href="#" class="brand-link {{ jazzmin_ui.brand_classes }}" id="jazzy-logo">
    <img src="{% static jazzmin_settings.site_logo %}" alt="{{ jazzmin_settings.site_header }} Logo" class="brand-image elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">{{ jazzmin_settings.site_header }}</span>
  </a>
  
  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        {% if jazzmin_settings.user_avatar %}
        <img src="{% get_user_avatar request.user %}" width="160px" class="img-circle elevation-2" alt="User Image">
        {% else %}
        <i class="fas fa-inverse user-profile fa-user-circle"></i>
        {% endif %}
      </div>
      
      <div class="info">
        {% if perms|can_view_self %}
        <a href="{% jazzy_admin_url request.user request.current_app|default:'admin' %}" class="d-block">{{ request.user }}</a>
        {% else %}
        <span class="d-block" style="color: white;">{{ request.user }}</span>
        {% endif %}
      </div>
    </div>
    
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
        <li class="nav-item">
          {% if request.user.is_staff %}
          <a href="{% url 'core:dashboard' %}" class="nav-link">
          {% else %}
          <a href="{% url 'akun:dashboard' %}" class="nav-link">
          {% endif %}
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>{% trans 'Dashboard' %}</p>
          </a>
        </li>

        <li class="nav-item">
          <a href="{% url 'akun:my_comment' %}" class="nav-link">
            <i class="fas fa-comments nav-icon"></i>
            <p>My Comments</p>
          </a>
        </li>

        {% if request.user.is_staff %}
        <li class="nav-header">Manage Content</li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="fas fa-home nav-icon"></i>
            <p>Blog Content <i class="fas fa-angle-left right"></i></p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
                <a href="{% url 'admin:posts_terms_changelist' %}" class="nav-link">
                  <i class="fas fa-cat nav-icon"></i>
                  <p>Category</p>
                </a>
                <a href="{% url 'admin:posts_posts_changelist' %}" class="nav-link">
                  <i class="fas fa-blog nav-icon"></i>
                    <p>Post</p>
                </a>
            </li>
        </ul>
        </li>

        <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="far fa-folder nav-icon"></i>
                <p>Content Section <i class="fas fa-angle-left right"></i></p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{% url 'admin:corecode_countersec_changelist' %}" class="nav-link">
                      <i class="fas fa-angle-double-right nav-icon"></i>
                      <p>Counter Section</p>
                    </a>
                    <a href="{% url 'admin:corecode_featured_changelist' %}" class="nav-link">
                      <i class="fas fa-angle-double-right nav-icon"></i>
                      <p>Featured Section</p>
                    </a>
                    <a href="{% url 'admin:corecode_intro_changelist' %}" class="nav-link">
                      <i class="fas fa-angle-double-right nav-icon"></i>
                      <p>Intro Section</p>
                    </a>
                    <a href="{% url 'admin:corecode_poster_changelist' %}" class="nav-link">
                      <i class="fas fa-angle-double-right nav-icon"></i>
                      <p>Poster Section</p>
                    </a>
                    <a href="{% url 'admin:corecode_progress_changelist' %}" class="nav-link">
                      <i class="fas fa-angle-double-right nav-icon"></i>
                      <p>Progress Section</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
          <a href="{% url 'admin:akun_comments_changelist' %}" class="nav-link">
            <i class="fas fa-comments nav-icon"></i>
            <p>All Comments</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'admin:corecode_contact_changelist' %}" class="nav-link">
            <i class="far fa-address-book nav-icon"></i>
            <p>Contact</p>
          </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'admin:posts_page_changelist' %}" class="nav-link">
              <i class="fas fa-asterisk nav-icon"></i>
                <p>Page Content</p>
            </a>
        </li>

        <li class="nav-header">Manage Product</li>
        <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-shopping-cart nav-icon"></i>
              <p>Order</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fab fa-product-hunt nav-icon"></i>
                <p>Product <i class="fas fa-angle-left right"></i></p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{% url 'admin:products_product_changelist' %}" class="nav-link">
                      <i class="fas fa-angle-double-right nav-icon"></i>
                      <p>Product</p>
                    </a>
                </li>
            </ul>
        </li>

        {% comment %}
        <li class="nav-header">SIB Mail</li>
        <li class="nav-item">
          <a href="{% url 'admin:sibmail_sibaccount_changelist' %}" class="nav-link">
            <i class="fas fa-key nav-icon"></i>
            <p>Api Key</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'sibmail:sib_account' %}" class="nav-link">
            <i class="fas fa-envelope nav-icon"></i>
            <p>Account</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'sibmail:my_contact' %}" class="nav-link">
            <i class="fas fa-id-card nav-icon"></i>
            <p>Subscriber</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'sibmail:get_email_campaigns' %}" class="nav-link">
            <i class="fas fa-mail-bulk nav-icon"></i>
            <p>Email Campaigns</p>
          </a>
        </li>
        {% endcomment %}

        <li class="nav-header">Manage User</li>
        <li class="nav-item">
          <a href="{% url 'admin:auth_user_changelist' %}" class="nav-link">
            <i class="far fa-user nav-icon"></i>
            <p>{% trans 'Users' %}</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'admin:auth_group_changelist' %}" class="nav-link">
            <i class="fas fa-users nav-icon"></i>
            <p>Group</p>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>