akun/urls.py
from django.urls import path, include
from akun import views

app_name = 'akun'

comment_url = [
    path('permanent/delete/comment/<pk>/', views.permanent_delete, name='delete_comment'),
    path('un/delete/comment/<pk>/', views.undelete_comment, name='undelete_comment'),
    path('soft/delete/comment/<pk>/', views.trash_comment, name='trash_comment'),
    path('make/comment/', views.PostComment.as_view(), name='comment_make'),
    path('get/comment/<str:hash>/', views.CommentsView.as_view(), name='comment_view'),
    path('my/comment/', views.MyComments.as_view(), name='my_comment'),
    path('is-spam/comment/delete/', views.all_spam_clean, name='all_spam_delete'),
]

i_update = [
    path('profile/', views.UpdateMyGeneralProfile.as_view(), name='update_profile'),
    path('bio/', views.UpdateOrCreateBio.as_view(), name='update_bio'),
]

urlpatterns = [
    path('comments/', include(comment_url)),
    path('signin/comment/', views.login_from_comment, name='comment_login'),
    path('update/', include(i_update)),
    path('', views.MyAkunView.as_view(), name='dashboard'),
]

akun/templates/akun/comment/comment.html
{% load widget_tweaks %}
<style>
    button.reply {
        border: none !important;
        background: none !important;
        text-decoration: underline !important;
        outline: none !important;
        font-weight: bold;
        color: #0275d8;;
    }
</style>
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <div><p class="comment-count comment-title mb-2">{{ count }} Comment(s)</p></div>
            <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        
        <div class="modal-body">
            <div class="col-md-12">
                {% for comment in comments %}
                    <div class="mb-2">
                        {% if comment.active %}
                        <div class="alert alert-primary" id="id-{{ comment.id }}">
                            <span>
                                <span class="ion-chatbox-working"></span> {% if comment.user %}{{ comment.user }}{% else %}{{ comment.nama | striptags | escape }}{% endif %} | 
                                <span class="ion-calendar"></span> 
                                <span style="font-size: 0.8em;"><a href="?comment={{ comment.id }}">{{ comment.cmdate | date:'d M Y H:i:s T' }}</a></span>
                            </span>
                            <p>{{ comment.teks | striptags | escape }} {{ comment.id }} {{ comment.reply_id }}</p>
                            <div>
                                <button type="button" value="{% url 'akun:comment_make' %}?room={{ hash }}&block={{ comment.id }}" class="comment reply">Jawab</button>
                            </div>
                        </div>
                        {% endif %}
                        
                        {% if comment.is_deleted %}
                        <div class="alert alert-primary" id="id-{{ comment.id }}">
                            <span>
                                <span class="ion-chatbox-working"></span> {% if comment.user %}{{ comment.user }}{% else %}{{ comment.nama | striptags | escape }}{% endif %} | 
                                <span class="ion-calendar"></span> 
                                <span style="font-size: 0.8em;"><a href="?comment={{ comment.id }}">{{ comment.cmdate | date:'d M Y H:i:s T' }}</a></span>
                            </span>
                            <p>
                                <em>Komentar ini telah dihapus</em> 
                                {% if request.user == comment.user %}
                                Oleh : Anda
                                {% endif %}
                            </p>
                        </div>
                        {% endif %}

                        {% for reply in comment.replies.all %}
                        {% if reply.active %}
                        <div class="row">
                            <div class="col ml-5" style="border-left: 2px solid #0275d8;">
                                <div class="alert alert-secondary" id="id-{{ reply.id }}">
                                    <span>
                                        <span class="ion-reply-all"></span> {% if reply.user %}{{ reply.user }}{% else %}{{ reply.nama | striptags | escape }}{% endif %} | 
                                        <span class="ion-calendar"></span> 
                                        <span style="font-size: 0.8em;"><a href="?comment={{ reply.id }}">{{ comment.cmdate | date:'d M Y H:i:s T' }}</a></span>
                                    </span>
                                    <p> {{ reply.teks | striptags | escape }} {{ reply.reply_id }}</p>
                                    <!-- <div>
                                        <button type="button" value="{% url 'akun:comment_make' %}?room={{ hash }}&block={{ reply.id }}" class="comment reply">Jawab</button>
                                    </div> -->
                                </div>
                            </div>
                        </div>
                        {% endif %}

                        {% if reply.is_deleted %}
                        <div class="row">
                            <div class="col ml-5" style="border-left: 2px solid #0275d8;">
                                <div class="alert alert-secondary" id="id-{{ reply.id }}">
                                    <span>
                                        <span class="ion-reply-all"></span> {% if reply.user %}{{ reply.user }}{% else %}{{ reply.nama | striptags | escape }}{% endif %} | 
                                        <span class="ion-calendar"></span> 
                                        <span style="font-size: 0.8em;"><a href="?comment={{ reply.id }}">{{ comment.cmdate | date:'d M Y H:i:s T' }}</a></span>
                                    </span>
                                    <p>
                                        <em>Komentar ini telah dihapus</em> 
                                        {% if request.user == comment.user %}
                                        Oleh : Anda
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                {% empty %}
                <div class="title-box-2">
                    <h5>Belum ada komentar</h5>
                    <button type="button" value="{% url 'akun:comment_make' %}?room={{ hash }}" class="btn btn-primary mb-4 comment">Comment</button>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">Tutup</span>
            </button>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('.comment').on('click', function(e){
            e.preventDefault();
            const xyz = $(this).val();
            $.ajax({
                url: xyz,
                contentType: false,
                cache: false,
                processData: false
            }).done(function(data){
                $('#myModal').modal('hide');
                $('#myModal').on('shown.bs.modal', function(){
                    $('#myModal').html(data);
                    $('#myForm').attr('action', xyz);
                });
                $('#myModal').modal('show');
            })
        });
    });
</script>

akun/templates/akun/comment/form.html
{% load i18n static widget_tweaks %}
<div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
        <div class="modal-header">
            {{ text_form }}
            <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
            <form method="POST" id="myForm">
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% csrf_token %}
                {{ form.media }}
                {% if form.errors %}
                    <div class="container">
                        <div class="alert alert-danger alert-dismissible">
                            {% if errors|length == 1 %}
                                {% trans "Please correct the error below." %}
                            {% else %}
                                {% trans "Please correct the errors below." %}
                            {% endif %}
                        </div>
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button>
                                <i class="icon fa fa-ban"></i>{{ error|capfirst }}
                            </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% for field in form.visible_fields %}
                <div class="form-group row mb-4">
                    <div class="col">
                        {% render_field field class="form-control" placeholder=field.label %}
                        {% if field.help_text %}
                        <div class="form-text text-muted"><small>{{ field.help_text }}</small></div>
                        {% endif %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <div class="alert alert-warning"><small>{{ error | striptags }}</small></div>
                        {% endfor %}
                        {% endif %}
                    </div>                    
                </div>
                {% endfor %}
                <div class="form-group row mb-4">
                    <div class="col">
                        <button class="btn btn-primary" type="submit">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        const frm = $('#myForm');
        
        $('#myForm').submit(function(e){
            e.preventDefault();
            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: new FormData(this),
                contentType: false,
                cache: false,
                processData: false
            }).done(function(data){
                if(data.err_code === 'invalid_form'){
                    for(var key in data.err_msg){
                        $(frm).find("input[id='id_"+key+"']").focus();
                        $(frm).find("div[class='alert alert-warning']").remove();
                        $(frm).find("input[id='id_"+key+"']").after('<div class="alert alert-warning"><small>'+data.err_msg[key][0])+'</small></div>';
                    }
                } else {
                    window.location.reload();
                }
            }).fail(function(xhr, textStatus, thrownError){
                const abc = xhr.responseText
                const swal_html = xhr.status == 406 ? '<p class="text-danger">' + abc.replace(/[^a-z0-9:]/gi,' ') + '</p>' : xhr.status == 500 ? '<div class="clearfix"></div>'+abc : false;
                const swal_width = xhr.status == 406 ? '75%' : xhr.status == 500 ? 'max-content' : false;
                Swal.fire({
                    html: swal_html,
                    title: thrownError + ' : ' + xhr.status,
                    icon: 'warning',
                    width: swal_width
                }).then(result => {
                    Swal.close()
                    // $('#comments').modal('hide');
                });
            });
            return false
        });

        $('.login-from-comment').on('click', function(e){
            e.preventDefault();
            swalTitle = "Login berhasil";
            const xyz = $(this).val();
            $.ajax({
                url: xyz,
                contentType: false,
                cache: false,
                processData: false
            }).done(function(data){
                $('#myModal').modal('hide');
                $('#myModal').on('shown.bs.modal', function(){
                    $('#myModal').html(data);
                });
                $('#myModal').modal('show');
            })
        });
    })
</script>

akun/templates/akun/comment/login.html
{% load i18n static widget_tweaks %}

<div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
        <div class="modal-header">
            {{ text_form }}
            <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
            <div class="row">
                <div class="col-sm-12">
                    <form method="POST" id="myForm" action="{% url 'account_login' %}" class="row row-cols-lg-auto g-3 align-items-center">
                        {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% csrf_token %}
                        {{ form.media }}
                        {% if form.errors %}
                            <div class="container">
                                <div class="alert alert-danger alert-dismissible">
                                    {% if errors|length == 1 %}
                                        {% trans "Please correct the error below." %}
                                    {% else %}
                                        {% trans "Please correct the errors below." %}
                                    {% endif %}
                                </div>
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button>
                                        <i class="icon fa fa-ban"></i>{{ error|capfirst }}
                                    </div>
                                {% endfor %}
                            </div>
                            {% endif %}
                        <div class="col-12 mb-3">
                            <div class="input-group">
                                {% render_field form.login class="form-control" placeholder=form.login.label %}
                            </div>
                        </div>

                        <div class="col-12 mb-3">
                            <div class="input-group">
                                {% render_field form.password class="form-control" placeholder=form.password.label %}
                            </div>
                        </div>

                        <div class="col-12 mb-3">
                            <div class="form-check">
                                {% render_field form.remember class="form-check-input" %}
                                <label class="form-check-label" for="{{ form.remember.id_for_label }}">{{ form.remember.label }}</label>
                            </div>
                            <div class="form-text text-muted"><small>{{ form.remember.help_text }}</small></div>
                        </div>

                        <div class="col-12 mb-3">
                            <button class="btn btn-primary" type="submit">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>