akun/urls.py
from django.urls import path, include
from akun import views

app_name = 'akun'

comment_url = [
    path('permanent/delete/comment/<pk>/', views.permanent_delete, name='delete_comment'),
    path('un/delete/comment/<pk>/', views.undelete_comment, name='undelete_comment'),
    path('soft/delete/comment/<pk>/', views.trash_comment, name='trash_comment'),
    path('make/comment/', views.PostComment.as_view(), name='comment_make'),
    path('get/comment/<str:hash>/', views.CommentsView.as_view(), name='comment_view'),
    path('my/comment/', views.MyComments.as_view(), name='my_comment'),
    path('is-spam/comment/delete/', views.all_spam_clean, name='all_spam_delete'),
]

i_update = [
    path('profile/', views.UpdateMyGeneralProfile.as_view(), name='update_profile'),
    path('bio/', views.UpdateOrCreateBio.as_view(), name='update_bio'),
]

urlpatterns = [
    path('comments/', include(comment_url)),
    path('signin/comment/', views.login_from_comment, name='comment_login'),
    path('update/', include(i_update)),
    path('', views.MyAkunView.as_view(), name='dashboard'),
]

akun/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator
from django.db import models
from django.db.models import Q, QuerySet
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext as _

from ckeditor.fields import RichTextField
from corecode.manager import CustomManager, TaggableManager, UUIDTaggedItem
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from posts.models import Posts
from uuid import uuid4

def upload_to_path(instance, filename):
    fname, dot, ext = filename.rpartition('.')
    slug_n = slugify(fname)
    slug_name = '{f}{d}{e}'.format(f=slug_n, d=dot, e=ext)
    return "photo/{0}/{1}".format(instance.akun.user.username, slug_name)

class AkunGroup(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid4, editable=False
    )
    name = models.CharField(
        max_length=25, default="Member", unique=True
    )

    def __str__(self) -> str:
        return self.name

class MyAkun(models.Model):
    class GenderChoices(models.TextChoices):
        PRIA = 'P', _('Male')
        WANITA = 'W', _('Female')
    id = models.UUIDField(
        primary_key=True, default=uuid4, editable=False
    )
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="account_profile"
    )
    alamat = models.CharField(
        max_length=255, null=True, blank=True
    )
    gender = models.CharField(
        max_length=10, choices=GenderChoices.choices,
        null=True, blank=False
    )
    akun_group = models.ForeignKey(
        AkunGroup, on_delete=models.SET_NULL, null=True
    )
    
    def __str__(self) -> str:
        return 'Profile {}'.format(self.user.username)

class BioAccount(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid4, editable=False
    )
    akun = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="account_bio"
    )
    skills = TaggableManager(
        blank=True, through=UUIDTaggedItem,
        verbose_name="skills"
    )
    short_bio = models.CharField(max_length=255)
    full_bio = RichTextField(null=True, blank=True)
    website = models.URLField(blank=True, null=True)

    def __str__(self) -> str:
        return "Bio {}".format(self.akun)

class PhotoAccount(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    akun = models.ForeignKey(User, on_delete=models.CASCADE, related_name="account_photo")
    photo = models.ImageField(upload_to=upload_to_path, blank=True, null=True)
    info = models.CharField(max_length=255, blank=True, null=True)
    uploaded = models.DateTimeField(auto_now_add=True)
    set_as_profile = models.BooleanField(default=True)

    avatar = ImageSpecField(
        source='photo',
        processors=[ResizeToFill(280,100)],
        format='WEBP',
        options={'quality': 75}
    )

    def save(self):
        if self.info == None:
            self.info = self.photo


    def __str__(self) -> str:
        return "{a} {i}".format(a=self.akun, i=self.info)

class SocialAccount(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    akun = models.ForeignKey(User, on_delete=models.CASCADE, related_name="account_social")
    name = models.CharField(max_length=50)
    url = models.URLField()

    def __str__(self) -> str:
        return "{n} {a}".format(n=self.name, a=self.akun)

class Comments(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE, related_name='comment')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='user_comment')
    nama = models.CharField(max_length=75, null=True, blank=False)
    email = models.EmailField(null=True, blank=False, help_text="Email tidak akan ditampilkan")
    teks = models.TextField(verbose_name="tulis komentar kamu", validators=[MaxLengthValidator(250)])
    cmdate = models.DateTimeField(auto_now_add=True, verbose_name="Comment date")
    active = models.BooleanField(default=False)
    reply = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='replies', blank=True, null=True)

    is_spam = models.BooleanField(default=False)

    is_deleted = models.BooleanField(default=False, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    deleted_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True,
        blank=True, related_name='user_delete_comment'
    )

    objects = CustomManager()
    all_objects = models.Manager()

    class QuerySet(QuerySet):
        def get_comments(self, hash, **kwargs):
            result = self.filter(
                Q(post=hash, active=True, reply=None) |
                Q(post=hash, is_deleted=True, reply=None),
                **kwargs
            )
            return result
        
        def comments_approve(self, user_id):
            return self.filter(user_id=user_id, active=True)
        
        def comments_unapprove(self, user_id):
            result = self.filter(
                Q(user_id=user_id, active=False) & (Q(is_deleted=False) | Q(is_deleted=None))
            )
            return result
        
        def comments_is_spam(self, user_id):
            result = self.filter(
                Q(user_id=user_id, is_spam=True) & (Q(is_deleted=False) | Q(is_deleted=None))
            )
            return result
        
        def comments_deleted(self, user_id):
            return self.filter(user_id=user_id, is_deleted=True)
    
    def soft_delete(self, user_id=None):
        self.active = False
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.deleted_by = user_id
        self.save()
    
    def undelete(self):
        self.active = False
        self.is_deleted = False
        self.deleted_at = None
        self.deleted_by = None
        self.save()
    
    def is_spam_comment(self):
        self.active = False
        self.is_spam = True
        self.save()

    class Meta:
        ordering = ['-cmdate']
    
    def __str__(self) -> str:
        if self.user:
            return 'Comment {} by {}'.format(self.post.title, self.user.username)
        else:
            return 'Comment {} by {}'.format(self.post.title, self.nama)

akun/templates/akun/profile/form.html
{% load static widget_tweaks %}
<div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
        <div class="modal-header">
            {{ text_form }}
            <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
            <form method="POST" id="myForm">
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% csrf_token %}
                {{ form.media }}
                {% if form.errors %}
                    <div class="container">
                        <div class="alert alert-danger alert-dismissible">
                            {% if errors|length == 1 %}
                                Please correct the error below.
                            {% else %}
                                Please correct the errors below.
                            {% endif %}
                        </div>
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button>
                                <i class="icon fa fa-ban"></i>{{ error|capfirst }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}

                {% for field in form.visible_fields %}
                <div class="form-group row mb-4">
                    <div class="col">
                        {% render_field field class="form-control" placeholder=field.label %}
                        {% if field.help_text %}
                        <div class="form-text text-muted"><small>{{ field.help_text }}</small></div>
                        {% endif %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <div class="alert alert-warning"><small>{{ error | striptags }}</small></div>
                        {% endfor %}
                        {% endif %}
                    </div>                    
                </div>
                {% endfor %}

                {% for field in form_um.visible_fields %}
                <div class="form-group row mb-4">
                    <div class="col">
                        {% render_field field class="form-control" placeholder=field.label %}
                        {% if field.help_text %}
                        <div class="form-text text-muted"><small>{{ field.help_text }}</small></div>
                        {% endif %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <div class="alert alert-warning"><small>{{ error | striptags }}</small></div>
                        {% endfor %}
                        {% endif %}
                    </div>                    
                </div>
                {% endfor %}
                
                {% for field in form_ge.visible_fields %}
                <div class="form-group row mb-4">
                    <div class="col">
                        {% render_field field class="form-control" placeholder=field.label %}
                        {% if field.help_text %}
                        <div class="form-text text-muted"><small>{{ field.help_text }}</small></div>
                        {% endif %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <div class="alert alert-warning"><small>{{ error | striptags }}</small></div>
                        {% endfor %}
                        {% endif %}
                    </div>                    
                </div>
                {% endfor %}
                <div class="form-group row mb-4">
                    <div class="col">
                        <button class="btn btn-primary" type="submit">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        const frm = $('#myForm');
        
        $('#myForm').submit(function(e){
            e.preventDefault();
            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: new FormData(this),
                contentType: false,
                cache: false,
                processData: false
            }).done(function(data){
                if(data.err_code === 'invalid_form'){
                    for(var key in data.err_msg){
                        $(frm).find("input[id='id_"+key+"']").focus();
                        $(frm).find("div[class='alert alert-warning']").remove();
                        $(frm).find("input[id='id_"+key+"']").after('<div class="alert alert-warning"><small>'+data.err_msg[key][0])+'</small></div>';
                    }
                    for(var key in data.err_msg[0]){
                        $(frm).find("input[id='id_"+key+"']").focus();
                        $(frm).find("div[class='alert alert-warning']").remove();
                        $(frm).find("input[id='id_"+key+"']").after('<div class="alert alert-warning"><small>'+data.err_msg[0][key][0])+'</small></div>';
                    }
                    for(var key in data.err_msg[1]){
                        $(frm).find("input[id='id_"+key+"']").focus();
                        $(frm).find("div[class='alert alert-warning']").remove();
                        $(frm).find("input[id='id_"+key+"']").after('<div class="alert alert-warning"><small>'+data.err_msg[1][key][0])+'</small></div>';
                    }
                } else {
                    window.location.reload();
                }
            }).fail(function(xhr, textStatus, thrownError){
                const abc = xhr.responseText
                const swal_html = xhr.status == 406 ? '<p class="text-danger">' + abc.replace(/[^a-z0-9:]/gi,' ') + '</p>' : xhr.status == 500 ? '<div class="clearfix"></div>'+abc : false;
                const swal_width = xhr.status == 406 ? '75%' : xhr.status == 500 ? 'max-content' : false;
                Swal.fire({
                    html: swal_html,
                    title: thrownError + ' : ' + xhr.status,
                    icon: 'warning',
                    width: swal_width
                }).then(result => {
                    Swal.close()
                    // $('#comments').modal('hide');
                });
            });
            return false
        });
    })
</script>

akun/templates/akun/profile/my_profile.html
{% extends 'admin/base_site.html' %}

{% load static %}
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'vendor/sweetalert2/sweetalert2.min.css' %}">
{% endblock %}

{% block page_title %}{% block title %}My Profile Account{% endblock %}{% endblock %}

{% block page_content %}
<div class="col-12">
    <div class="card mb-4">
        <div class="card-header">
            <nav>
                <div class="nav nav-pills nav-profile mb-3" id="myProfile" role="tablist">
                    <a class="nav-link active" id="a-general-tab" data-toggle="tab" href="#general-tab" role="tab" aria-controls="general-tab"><i class="fas fa-user"></i> General</a>
                    
                    <a class="nav-link" id="a-about-tab" data-toggle="tab" href="#about-tab" role="tab" aria-controls="about-tab"><i class="fas fa-address-card"></i> About Me</a>
                    
                    <a class="nav-link" id="a-picture-tab" data-toggle="tab" href="#picture-tab" role="tab" aria-controls="picture-tab"><i class="fas fa-images"></i> Picture</a>
                    
                    <a class="nav-link" id="a-social-tab" data-toggle="tab" href="#social-tab" role="tab" aria-controls="social-tab"><i class="fas fa-icons"></i> Social Account</a>
                </div>
            </nav>
        </div>
        <div class="card-body">
            <div class="tab-content" id="content-myProfile">
                <div class="tab-pane fade show active" id="general-tab" role="tabpanel" aria-labelledby="a-general-tab">
                    <table class="table-sm">
                        <tr>
                            <td>Username</td>
                            <td>:</td>
                            <td>{{ akun.username }}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>:</td>
                            <td>{{ akun.email }}</td>
                        </tr>
                        <tr>
                            <td>Name</td>
                            <td>:</td>
                            <td>
                                {% if akun.first_name %}
                                {{ akun.get_full_name }}
                                {% else %}
                                link
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>Birthday</td>
                            <td>:</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Gender</td>
                            <td>:</td>
                            <td>{{ akun.account_profile.get_gender_display }}</td>
                        </tr>
                        <tr>
                            <td>Address</td>
                            <td>:</td>
                            <td>
                                {% if akun.account_profile.alamat %}
                                {{ akun.account_profile.alamat }}
                                {% endif %}
                            </td>
                        </tr>
                    </table>
                    <div class="col">
                        <button type="button" class="btn btn-primary update" value="{% url 'akun:update_profile' %}">
                            Update
                        </button>
                    </div>
                </div>
                <div class="tab-pane fade" id="about-tab" role="tabpanel" aria-labelledby="a-about-tab">
                    <table class="table-sm">
                        <tr>
                            <td>Skills</td>
                            <td>:</td>
                            <td>
                                {% for t in akun.account_bio.skills.all %}
                                {{ t.name }},&nbsp;
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td>Short Bio</td>
                            <td>:</td>
                            <td>{{ akun.account_bio.short_bio }}</td>
                        </tr>
                        <tr>
                            <td>Full Bio</td>
                            <td>:</td>
                            <td>{{ akun.account_bio.full_bio }}
                            </td>
                        </tr>
                        <tr>
                            <td>Website</td>
                            <td>:</td>
                            <td>{{ akun.account_bio.website }}</td>
                        </tr>
                    </table>
                    <div class="col">
                        <button type="button" class="btn btn-primary update" value="{% url 'akun:update_bio' %}">
                            Update
                        </button>
                    </div>
                </div>
                <div class="tab-pane fade" id="picture-tab" role="tabpanel" aria-labelledby="a-picture-tab">
                    My Picture
                </div>
                <div class="tab-pane fade" id="social-tab" role="tabpanel" aria-labelledby="a-social-tab">
                    Social Account
                </div>
            </div>
        </div>
        
        <div class="card-footer clearfix">
            Last Login : {{ akun.last_login }}
            </tr>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
<script src="{% static 'vendor/sweetalert2/sweetalert2.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $('.update').on('click', function(e){
            e.preventDefault();
            const xyz = $(this).val();
            $.ajax({
                url: xyz,
                contentType: false,
                cache: false,
                processData: false
            }).done(function(data){
                $('#myModal').modal('hide');
                $('#myModal').on('shown.bs.modal', function(){
                    $('#myModal').html(data);
                    $('#myForm').attr('action', xyz);
                });
                $('#myModal').modal('show');
            })
        });
    });
</script>
{% endblock %}