sibmail/urls.py
from django.urls import path, include
from sibmail import views

app_name = 'sibmail'

get_email = [
    path('get-email-campaigns/', views.MySIBGetEmailCampaigns.as_view(), name='get_email_campaigns'),
]

urlpatterns = [
    path('contact/delete/<str:email>/', views.delete_contact, name='contact_delete'),
    path('contact/create/', views.CreateAContact.as_view(), name='create_contact'),
    path('contact/create/success/', views.success_subscribe, name='sub_success'),
    path('contact/details/', views.MySIBContactDetails.as_view(), name='my_contact_details'),
    path('contact/', views.MySIBContact.as_view(), name='my_contact'),
    path('my-account/', views.MySIBAccount.as_view(), name='sib_account'),
    
    path('get-all-folders/', views.GetAllFolders.as_view(), name='get_all_folders'),
    path('get-list-in-folders/<int:fid>/', views.GetListInFolder.as_view(), name='get_linfold'),

    path('get/', include(get_email)),
]

sibmail/models.py
from uuid import uuid4
from django.db import models

class SibAccount(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    api_key = models.CharField(
        max_length=255,
        help_text="Dapatkan API-KEY di <a href='https://www.sendinblue.com/?tap_a=30591-fb13f0&tap_s=2662645-7d6da9' target='_blank' rel='noopener'>Send In Blue</a>"
    )

    class Meta:
        verbose_name_plural = "API KEY"

    def __str__(self) -> str:
        return self.api_key

sibmail/forms.py
from django import forms

class FormGetAllFolders(forms.Form):
    lmt = forms.NumberInput()
    oft = forms.NumberInput()
    srt = forms.TextInput()

class FormCreateContact(forms.Form):
    email = forms.EmailField(label="Email")
    fname = forms.CharField(max_length=50, label="Nama lengkap")
    optin = forms.BooleanField(
        label="Setuju menerima pemberitahuan content terbaru dan promosi",
        help_text="Kamu bisa unsubscribe (berhenti berlangganan) kapan saja"
    )

sibmail/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic import TemplateView, View
# from django.views.generic.edit import FormMixin

from datetime import datetime, timedelta

from corecode.shortcuts import required_ajax
from corecode.utils import LoginMixin, IsStaffPermissionMixin
from sibmail import (
    config as config_sib, forms as frm
)

def success_subscribe(request):
    return render(request, 'sibmail/manage/success.html')

class MySIBAccount(LoginMixin, IsStaffPermissionMixin, TemplateView):
    permission_required = 'is_staff'
    template_name = 'sibmail/manage/account.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MySIBAccount, self).get_context_data(*args, **kwargs)
        respons = config_sib.get_sib_account()
        context['account'] = respons
        return context

class MySIBContact(LoginMixin, IsStaffPermissionMixin, TemplateView):
    permission_required = 'is_staff'
    template_name = 'sibmail/manage/contact.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MySIBContact, self).get_context_data(*args, **kwargs)
        respons = config_sib.get_sib_contact()
        context['contact'] = respons
        return context

class MySIBContactDetails(LoginMixin, IsStaffPermissionMixin, TemplateView):
    permission_required = 'is_staff'
    template_name = 'sibmail/manage/contact_details.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MySIBContactDetails, self).get_context_data(*args, **kwargs)
        email = self.request.GET.get('email')
        respons = config_sib.get_contact_details(email)
        context['contact'] = respons
        return context

class MySIBGetEmailCampaigns(LoginMixin, IsStaffPermissionMixin, TemplateView):
    permission_required = 'is_staff'
    template_name = 'sibmail/email/all-campaigns.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MySIBGetEmailCampaigns, self).get_context_data(*args, **kwargs)
        start_date = datetime.now()
        end_date = start_date - timedelta(days=129)
        options = {
            "type": 'classic',
            # "status": '',
            # "start_date": '',
            # "end_date": '',
            "limit": 500,
            "offset": 0,
            "sort": "desc"
        }
        campaigns = config_sib.get_all_email_campaigns(**options)
        context['campaigns'] = campaigns
        return context

class GetAllFolders(LoginMixin, IsStaffPermissionMixin, TemplateView):
    permission_required = 'is_staff'
    template_name = 'sibmail/block/folders.html'
    # form_class = frm.FormGetAllFolders

    def get_context_data(self, *args, **kwargs):
        limit = 10
        offset = 0
        sorts = 'desc'
        context = super(GetAllFolders, self).get_context_data(*args, **kwargs)
        folders = config_sib.get_all_folders(limit, offset, sorts)
        context['folders'] = folders
        return context

    # def get(self, *args, **kwargs):
    #     limit = 10
    #     offset = 0
    #     sorts = 'desc'

    #     # if self.request.GET.get('limit'):
    #     #     limit = self.request.GET.get('limit')
        
    #     # if self.request.GET.get('offset'):
    #     #     offset = self.request
    #     # if self.request.GET.get('sort'):
    #     #     sorts = self.request.GET.get('sort')
        
    #     folders = config_sib.get_all_folders(limit, offset, sorts)
    #     return {"folders": folders, "form": self.form_class} 

class GetListInFolder(LoginMixin, IsStaffPermissionMixin, TemplateView):
    template_name = 'sibmail/block/list-in-folder.html'

    def get_context_data(self, *args, **kwargs):
        fid = self.kwargs['fid']
        limit = 10

        context = super(GetListInFolder, self).get_context_data(*args, **kwargs)
        in_folder = config_sib.get_list_in_folder(fid, limit)
        context['in_folder'] = in_folder
        return context

class CreateAContact(View):
    template_name = 'sibmail/manage/form.html'
    success_url = reverse_lazy('sibmail:sub_success')

    def get_success_uri(self):
        url = self.request.build_absolute_uri(self.success_url)
        return url

    @method_decorator(required_ajax)
    def get(self, *args, **kwargs):
        form = frm.FormCreateContact
        txt_form = "Subscribe Content"
        context = {
            "text_form": txt_form,
            "form": form
        }
        return render(self.request, self.template_name, context)
    
    def form_invalid(self, form):
        context = {
            'success': False,
            'err_code': 'invalid_form',
            'err_msg': form.errors
        }
        return JsonResponse(context, safe=False)
    
    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        fname = form.cleaned_data.get('fname')
        optin = form.cleaned_data.get('optin')

        # config_sib.create_a_contact(email, FIRSTNAME=fname, OPT_IN=optin)

        config_sib.create_contact_doi(
            email=email,
            success_url=self.get_success_uri(),
            FIRSTNAME=fname
        )
        
        return JsonResponse("OK", status=200, safe=False)
    
    @method_decorator(required_ajax)
    def post(self, *args, **kwargs):
        form = frm.FormCreateContact(self.request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

@required_ajax
def delete_contact(request, email):
    config_sib.delete_contact(email)
    return JsonResponse("OK", status=200, safe=False)

sibmail/templates/block/folders.html
{% load static %}
<!-- <div class="col">
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
            <div class="col">
                {{ form }}
            </div>
            {% endfor %}
        
            <div class="col">
                <input type="submit" value="Filter" class="btn btn-primary">
            </div>
        </div>
    </form>
</div> -->
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'vendor/sweetalert2/sweetalert2.min.css' %}">
{% endblock %}

<div class="col-12">
    <p>Folder Count: {{ folders.count }}</p>
    <table class="table table-sm">
        <thead>
            <tr>
                <th>Name</th>
                <th>Blacklisted</th>
                <th>Subscribers</th>
                <th>Unique Subscribers</th>
            </tr>
        </thead>
        <tbody>
            {% for fdr in folders.folders %}
            <tr>
                <td>
                    <button type="button" value="{% url 'sibmail:get_linfold' fdr.id %}" class="btn btn-link in-folder">
                        {{ fdr.name }}
                    </button>
                    </td>
                <td>{{ fdr.totalBlacklisted }}</td>
                <td>{{ fdr.totalSubscribers }}</td>
                <td>{{ fdr.uniqueSubscribers }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% block extrajs %}
<script src="{% static 'vendor/sweetalert2/sweetalert2.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $('.in-folder').on('click', function(e){
            e.preventDefault();
            const url = $(this).val();
            $.ajax({
                url: url
            }).done(function(respon){
                Swal.fire({
                    title: 'List in folder',
                    html: respon,
                    width: 'max-content'
                })
            })
        })
    })
</script>
{% endblock %}

sibmail/templates/block/form.html
<!-- Begin Sendinblue Form -->
<!-- START - We recommend to place the below code in head tag of your website html  -->
<style>
    @font-face {
      font-display: block;
      font-family: Roboto;
      src: url(https://assets.sendinblue.com/font/Roboto/Latin/normal/normal/7529907e9eaf8ebb5220c5f9850e3811.woff2) format("woff2"), url(https://assets.sendinblue.com/font/Roboto/Latin/normal/normal/25c678feafdc175a70922a116c9be3e7.woff) format("woff")
    }
  
    @font-face {
      font-display: fallback;
      font-family: Roboto;
      font-weight: 600;
      src: url(https://assets.sendinblue.com/font/Roboto/Latin/medium/normal/6e9caeeafb1f3491be3e32744bc30440.woff2) format("woff2"), url(https://assets.sendinblue.com/font/Roboto/Latin/medium/normal/71501f0d8d5aa95960f6475d5487d4c2.woff) format("woff")
    }
  
    @font-face {
      font-display: fallback;
      font-family: Roboto;
      font-weight: 700;
      src: url(https://assets.sendinblue.com/font/Roboto/Latin/bold/normal/3ef7cf158f310cf752d5ad08cd0e7e60.woff2) format("woff2"), url(https://assets.sendinblue.com/font/Roboto/Latin/bold/normal/ece3a1d82f18b60bcce0211725c476aa.woff) format("woff")
    }
  
    #sib-container input:-ms-input-placeholder {
      text-align: left;
      font-family: "Helvetica", sans-serif;
      color: #c0ccda;
    }
  
    #sib-container input::placeholder {
      text-align: left;
      font-family: "Helvetica", sans-serif;
      color: #c0ccda;
    }
  
    #sib-container textarea::placeholder {
      text-align: left;
      font-family: "Helvetica", sans-serif;
      color: #c0ccda;
    }
  </style>
  <link rel="stylesheet" href="https://sibforms.com/forms/end-form/build/sib-styles.css">
  <!--  END - We recommend to place the above code in head tag of your website html -->
  
  <!-- START - We recommend to place the below code where you want the form in your website html  -->
  <div class="sib-form" style="text-align: center;
           background-color: #636969;                                 ">
    <div id="sib-form-container" class="sib-form-container">
      <div id="error-message" class="sib-form-message-panel" style="font-size:16px; text-align:left; font-family:Helvetica, sans-serif; color:#661d1d; background-color:#ffeded; border-radius:3px; border-color:#ff4949;max-width:540px;">
        <div class="sib-form-message-panel__text sib-form-message-panel__text--center">
          <svg viewBox="0 0 512 512" class="sib-icon sib-notification__icon">
            <path d="M256 40c118.621 0 216 96.075 216 216 0 119.291-96.61 216-216 216-119.244 0-216-96.562-216-216 0-119.203 96.602-216 216-216m0-32C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm-11.49 120h22.979c6.823 0 12.274 5.682 11.99 12.5l-7 168c-.268 6.428-5.556 11.5-11.99 11.5h-8.979c-6.433 0-11.722-5.073-11.99-11.5l-7-168c-.283-6.818 5.167-12.5 11.99-12.5zM256 340c-15.464 0-28 12.536-28 28s12.536 28 28 28 28-12.536 28-28-12.536-28-28-28z" />
          </svg>
          <span class="sib-form-message-panel__inner-text">
                            Formulir Anda tidak dapat disimpan. Silakan coba lagi.
                        </span>
        </div>
      </div>
      <div></div>
      <div id="success-message" class="sib-form-message-panel" style="font-size:16px; text-align:left; font-family:Helvetica, sans-serif; color:#085229; background-color:#e7faf0; border-radius:3px; border-color:#13ce66;max-width:540px;">
        <div class="sib-form-message-panel__text sib-form-message-panel__text--center">
          <svg viewBox="0 0 512 512" class="sib-icon sib-notification__icon">
            <path d="M256 8C119.033 8 8 119.033 8 256s111.033 248 248 248 248-111.033 248-248S392.967 8 256 8zm0 464c-118.664 0-216-96.055-216-216 0-118.663 96.055-216 216-216 118.664 0 216 96.055 216 216 0 118.663-96.055 216-216 216zm141.63-274.961L217.15 376.071c-4.705 4.667-12.303 4.637-16.97-.068l-85.878-86.572c-4.667-4.705-4.637-12.303.068-16.97l8.52-8.451c4.705-4.667 12.303-4.637 16.97.068l68.976 69.533 163.441-162.13c4.705-4.667 12.303-4.637 16.97.068l8.451 8.52c4.668 4.705 4.637 12.303-.068 16.97z" />
          </svg>
          <span class="sib-form-message-panel__inner-text">
                            Anda berhasil berlangganan
                        </span>
        </div>
      </div>
      <div></div>
      <div id="sib-container" class="sib-container--large sib-container--vertical" style="text-align:center; background-color:rgba(255,255,255,1); max-width:540px; border-radius:25px; border-width:10px; border-color:#0e82ec; border-style:solid;">
        <form id="sib-form" method="POST" action="https://58ff3ed5.sibforms.com/serve/MUIEANB0f-pr-wDNAiaPGXZ1R1o6s3P_P3sQVii-CrBwVKMk6PDw3ecybiEf4JNfYsHaPB69bfDWWY1yEsoHXNFNWmfFHQMlObRPT_hKoikweu4Z8EJM4RfLjQ2v0MPxrEu_RUen5Jgdnb-irmUn6yS7UsDVQIfnPsLwnxwz4fd7sxikeZCr7Nm-fkGeQ3nr0da5NGkWz6ae3rsm" data-type="subscription">
          <div style="padding: 8px 0;">
            <div class="sib-form-block" style="font-size:31px; text-align:center; font-weight:700; font-family:Helvetica, sans-serif; color:#0e82ec; background-color:transparent;">
              <p>Subscribe Content</p>
            </div>
          </div>
          <div style="padding: 8px 0;">
            <div class="sib-input sib-form-block">
              <div class="form__entry entry_block">
                <div class="form__label-row ">
                  <label class="entry__label" style="font-size:16px; text-align:left; font-weight:700; font-family:Helvetica, sans-serif; color:#0e82ec;" for="EMAIL" data-required="*">
                    Email yang sering digunakan
                  </label>
  
                  <div class="entry__field">
                    <input class="input" type="text" id="EMAIL" name="EMAIL" autocomplete="off" placeholder="EMAIL" data-required="true" required />
                  </div>
                </div>
  
                <label class="entry__error entry__error--primary" style="font-size:16px; text-align:left; font-family:Helvetica, sans-serif; color:#661d1d; background-color:#ffeded; border-radius:3px; border-color:#ff4949;">
                </label>
              </div>
            </div>
          </div>
          <div style="padding: 8px 0;">
            <div class="sib-input sib-form-block">
              <div class="form__entry entry_block">
                <div class="form__label-row ">
                  <label class="entry__label" style="font-size:16px; text-align:left; font-weight:700; font-family:Helvetica, sans-serif; color:#0e82ec;" for="FIRSTNAME" data-required="*">
                    Nama lengkap
                  </label>
  
                  <div class="entry__field">
                    <input class="input" maxlength="200" type="text" id="FIRSTNAME" name="FIRSTNAME" autocomplete="off" placeholder="NAMA LENGKAP" data-required="true" required />
                  </div>
                </div>
  
                <label class="entry__error entry__error--primary" style="font-size:16px; text-align:left; font-family:Helvetica, sans-serif; color:#661d1d; background-color:#ffeded; border-radius:3px; border-color:#ff4949;">
                </label>
              </div>
            </div>
          </div>
          <div style="padding: 8px 0;">
            <div class="sib-optin sib-form-block" data-required="true">
              <div class="form__entry entry_mcq">
                <div class="form__label-row ">
                  <label class="entry__label" style="font-size:16px; text-align:left; font-weight:700; font-family:Helvetica, sans-serif; color:#0e82ec;" for="OPT_IN" data-required="*">
                    Opt-in
                  </label>
                  <div class="entry__choice">
                    <label>
                      <input type="checkbox" class="input_replaced" value="1" id="OPT_IN" name="OPT_IN" required />
                      <span class="checkbox checkbox_tick_positive"></span><span style="font-size:14px; text-align:left; font-family:Helvetica, sans-serif; color:#042f98; background-color:transparent;"><p>Setuju menerima pemberitahuan content terbaru dan promosi</p></span> </label>
                  </div>
                </div>
                <label class="entry__error entry__error--primary" style="font-size:16px; text-align:left; font-family:Helvetica, sans-serif; color:#661d1d; background-color:#ffeded; border-radius:3px; border-color:#ff4949;">
                </label>
                <label class="entry__specification" style="font-size:12px; text-align:left; font-family:Helvetica, sans-serif; color:#0e82ec;">
                  Kamu bisa unsubscribe (berhenti berlangganan) kapan saja
                </label>
              </div>
            </div>
          </div>
          <div style="padding: 8px 0;">
            <div class="sib-form-block" style="text-align: left">
              <button class="sib-form-block__button sib-form-block__button-with-loader" style="font-size:16px; text-align:left; font-weight:700; font-family:Helvetica, sans-serif; color:#FFFFFF; background-color:#0e82ec; border-radius:4px; border-width:0px;" form="sib-form" type="submit">
                <svg class="icon clickable__icon progress-indicator__icon sib-hide-loader-icon" viewBox="0 0 512 512">
                  <path d="M460.116 373.846l-20.823-12.022c-5.541-3.199-7.54-10.159-4.663-15.874 30.137-59.886 28.343-131.652-5.386-189.946-33.641-58.394-94.896-95.833-161.827-99.676C261.028 55.961 256 50.751 256 44.352V20.309c0-6.904 5.808-12.337 12.703-11.982 83.556 4.306 160.163 50.864 202.11 123.677 42.063 72.696 44.079 162.316 6.031 236.832-3.14 6.148-10.75 8.461-16.728 5.01z" />
                </svg>
                SUBSCRIBE
              </button>
            </div>
          </div>
  
          <input type="text" name="email_address_check" value="" class="input--hidden">
          <input type="hidden" name="locale" value="en">
        </form>
      </div>
    </div>
  </div>
  <!-- END - We recommend to place the below code where you want the form in your website html  -->
  
  <!-- START - We recommend to place the below code in footer or bottom of your website html  -->
  <script>
    window.REQUIRED_CODE_ERROR_MESSAGE = 'Please choose a country code';
    window.LOCALE = 'en';
    window.EMAIL_INVALID_MESSAGE = window.SMS_INVALID_MESSAGE = "Informasi yang diberikan tidak valid. Harap tinjau format bidang dan coba lagi.";
  
    window.REQUIRED_ERROR_MESSAGE = "Bidang ini tidak boleh kosong. ";
  
    window.GENERIC_INVALID_MESSAGE = "Informasi yang diberikan tidak valid. Harap tinjau format bidang dan coba lagi.";
  
  
  
  
    window.translation = {
      common: {
        selectedList: '{quantity} list selected',
        selectedLists: '{quantity} lists selected'
      }
    };
  
    var AUTOHIDE = Boolean(0);
  </script>
  <script src="https://sibforms.com/forms/end-form/build/main.js"></script>
  
  <script src="https://www.google.com/recaptcha/api.js?hl=en"></script>
  
  <!-- END - We recommend to place the above code in footer or bottom of your website html  -->
  <!-- End Sendinblue Form -->

sibmail/templates/block/list-in-folder.html
<div class="col-12">
    <p>List count: {{ in_folder.count }} </p>
    <table class="table table-sm">
        <thead>
            <tr>
                <th>Name</th>
                <th>Blacklisted</th>
                <th>Subscribers</th>
                <th>Unique Subscribers</th>
            </tr>
        </thead>
        <tbody>
            {% for fdr in in_folder.lists %}
            <tr>
                <td>
                    <button type="button" value="{% url 'sibmail:get_linfold' fdr.id %}" class="btn btn-link in-folder">
                        {{ fdr.name }}
                    </button>
                    </td>
                <td>{{ fdr.totalBlacklisted }}</td>
                <td>{{ fdr.totalSubscribers }}</td>
                <td>{{ fdr.uniqueSubscribers }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>